"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(BASE_DIR / ".env")

# Everything that must survive a redeploy (the SQLite DB + uploaded media)
# lives under here. Runflare rebuilds this container's filesystem from
# scratch on every deploy, so a persistent disk MUST be mounted at this
# exact path — see DATA_DIR below — or uploads/data vanish every time.
# Defaults to a plain subdirectory for local dev, where persistence across
# rebuilds isn't a concern.
DATA_DIR = Path(env("DATA_DIR", default=str(BASE_DIR / "data")))
DATA_DIR.mkdir(parents=True, exist_ok=True)

# SECURITY WARNING: keep the secret key used in production secret!
# The fallback below is only ever used for local/dev convenience — real
# deployments must set DJANGO_SECRET_KEY in the environment.
SECRET_KEY = env(
    "DJANGO_SECRET_KEY",
    default="django-insecure-3s^3nt@74c1x=!6r1_3tcyqwrte1wu3qa%ghbau&4gjk8z$8^c",
)

# Secure by default: production deployments must explicitly opt in to DEBUG
# via env, rather than opt out of it.
DEBUG = env.bool("DJANGO_DEBUG", default=False)

# The Runflare domain is baked in as a fallback (not just read from
# backend/.env) because that file is gitignored and has, at least once,
# failed to make it into a Runflare deploy — this way the site still works
# even if a future deploy silently drops it. DJANGO_ALLOWED_HOSTS in the
# environment/`.env` still overrides this when present.
ALLOWED_HOSTS = env.list(
    "DJANGO_ALLOWED_HOSTS",
    default=["localhost", "127.0.0.1", "monadian3.runflare.run", "backend.monadianfath.com"],
)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "contact",
    "holdings",
    "portfolio",
    "newsletter",
    "careers",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # Serves STATIC_ROOT directly from the app process — needed because this
    # deploys as a single container behind Runflare with no nginx in front,
    # so nothing else is serving /static/.
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# The Next.js origin(s) allowed to call this API. Same reasoning as
# ALLOWED_HOSTS above — the Runflare frontend origin is baked in as a
# fallback in case backend/.env doesn't make it into a deploy.
CORS_ALLOWED_ORIGINS = env.list(
    "CORS_ALLOWED_ORIGINS",
    default=[
        "http://localhost:3000",
        "http://127.0.0.1:3000",
        "https://monadian2.runflare.run",
        "https://monadianfath.com",
    ],
)

CSRF_TRUSTED_ORIGINS = env.list(
    "CSRF_TRUSTED_ORIGINS",
    default=[
        "https://monadian2.runflare.run",
        "https://monadian3.runflare.run",
        "https://monadianfath.com",
        "https://backend.monadianfath.com",
    ],
)

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# The Runflare Postgres URL is baked in as a fallback (same reasoning as
# ALLOWED_HOSTS/CORS/CSRF above) — DATABASE_URL in the environment still
# overrides this when present. Local dev pins DATABASE_URL to sqlite in
# docker-compose.yml, so this default never applies there.
DATABASES = {
    "default": env.db(
        "DATABASE_URL",
        default="postgresql://postgres:kCa4r4SoHnPy3PcKhFyr@monadian-db-psi-service:5432/monadianeci_db",
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "fa"

TIME_ZONE = "Asia/Tehran"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Uploaded images (holding company logos, portfolio images, etc).
MEDIA_URL = "media/"
MEDIA_ROOT = DATA_DIR / "media"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 50,
    # Scope used by the public contact-form endpoint to prevent spam/abuse.
    "DEFAULT_THROTTLE_RATES": {"contact": "5/hour", "newsletter": "10/hour", "careers": "5/hour"},
}

# Production hardening. TLS is terminated at the platform's edge proxy, not
# by gunicorn itself, so SECURE_PROXY_SSL_HEADER tells Django to trust the
# X-Forwarded-Proto header when deciding if a request is secure — IF the
# proxy actually sends one. Runflare's does not, so SECURE_SSL_REDIRECT
# defaults to False here (an infinite redirect loop otherwise, since Django
# would never see its own request as secure); override via env if a future
# proxy in front of this does send that header correctly.
if not DEBUG:
    SECURE_SSL_REDIRECT = env.bool("SECURE_SSL_REDIRECT", default=False)
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    # The admin panel (the only thing here using session/CSRF cookies) is
    # served over plain HTTP on its current domain, with no HTTPS need for
    # it - a "Secure" cookie would be silently dropped by the browser on an
    # HTTP connection, breaking admin login with "CSRF cookie not set."
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"
    # No HSTS: it would make browsers refuse plain HTTP for this domain (and
    # all subdomains) for a year after a single successful HTTPS hit, which
    # actively works against not needing SSL here.
    # Drop the browsable API HTML renderer in production; JSON only.
    REST_FRAMEWORK["DEFAULT_RENDERER_CLASSES"] = ["rest_framework.renderers.JSONRenderer"]

# 12-factor logging: send everything to stdout/stderr for Docker to capture.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {"console": {"class": "logging.StreamHandler"}},
    "root": {"handlers": ["console"], "level": "INFO"},
}
