# Generated by Django 6.0.7 on 2026-07-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CareerApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=150, verbose_name="نام و نام خانوادگی"),
                ),
                ("age", models.PositiveSmallIntegerField(verbose_name="سن")),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="شماره تلفن"),
                ),
                (
                    "messengers",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="پیام\u200cرسان\u200cهای فعال",
                    ),
                ),
                (
                    "virtual_contact",
                    models.TextField(
                        verbose_name="شماره تماس مجازی با ذکر نام پیام\u200cرسان"
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("مجرد", "مجرد"),
                            ("متأهل", "متأهل"),
                            ("سایر", "سایر"),
                        ],
                        max_length=10,
                        verbose_name="وضعیت تأهل",
                    ),
                ),
                (
                    "education",
                    models.TextField(verbose_name="میزان تحصیلات، رشته و نام دانشگاه"),
                ),
                (
                    "desired_roles",
                    models.JSONField(
                        blank=True, default=list, verbose_name="همکاری مد نظر"
                    ),
                ),
                (
                    "is_reviewed",
                    models.BooleanField(default=False, verbose_name="بررسی شده"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ثبت"),
                ),
            ],
            options={
                "verbose_name": "درخواست همکاری",
                "verbose_name_plural": "درخواست\u200cهای همکاری",
                "ordering": ["-created_at"],
            },
        ),
    ]
