# Generated by Django 6.0.7 on 2026-07-25 16:58

import careers.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("careers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="careerapplication",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=careers.models.photo_upload_path,
                verbose_name="عکس",
            ),
        ),
        migrations.AddField(
            model_name="careerapplication",
            name="resume",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=careers.models.resume_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "doc", "docx"]
                    )
                ],
                verbose_name="رزومه",
            ),
        ),
        migrations.AlterField(
            model_name="careerapplication",
            name="virtual_contact",
            field=models.TextField(
                blank=True, verbose_name="شماره تماس مجازی با ذکر نام پیام\u200cرسان"
            ),
        ),
    ]
