# Generated by Django 6.0.7 on 2026-07-25 17:23

import careers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("careers", "0002_careerapplication_photo_careerapplication_resume_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="careerapplication",
            name="photo",
            field=models.ImageField(
                default="",
                upload_to=careers.models.photo_upload_path,
                verbose_name="عکس",
            ),
            preserve_default=False,
        ),
    ]
