# Generated by Django 6.0.7 on 2026-08-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("careers", "0004_alter_careerapplication_resume"),
    ]

    operations = [
        migrations.AddField(
            model_name="careerapplication",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("مرد", "مرد"), ("زن", "زن")],
                max_length=10,
                verbose_name="جنسیت",
            ),
        ),
    ]
