# Generated by Django 6.0.7 on 2026-07-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PortfolioItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(max_length=100, verbose_name="دسته\u200cبندی"),
                ),
                ("title", models.CharField(max_length=300, verbose_name="عنوان")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="portfolio/",
                        verbose_name="تصویر",
                    ),
                ),
                ("link", models.URLField(blank=True, verbose_name="لینک")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "نمونه کار",
                "verbose_name_plural": "نمونه کارها",
                "ordering": ["order", "-id"],
            },
        ),
    ]
