# Generated by Django 6.0.7 on 2026-07-07 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolioitem_description_portfolioitem_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام دسته\u200cبندی')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی نمونه کار',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای نمونه کار',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='category',
            field=models.CharField(blank=True, max_length=100, verbose_name='دسته\u200cبندی (قدیمی)'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='category_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='portfolio.portfoliocategory', verbose_name='دسته\u200cبندی'),
        ),
    ]
