# Generated by Django 6.0.7 on 2026-07-11 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_finalize_category_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='client',
            field=models.CharField(blank=True, max_length=200, verbose_name='کارفرما'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='date',
            field=models.CharField(blank=True, help_text='مثال: بهار سال ۱۴۰۵', max_length=100, verbose_name='تاریخ انجام پروژه'),
        ),
        migrations.CreateModel(
            name='PortfolioService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان خدمت')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('portfolio_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='portfolio.portfolioitem', verbose_name='نمونه کار')),
            ],
            options={
                'verbose_name': 'خدمت ارائه شده',
                'verbose_name_plural': 'لیست خدمات ارائه شده',
                'ordering': ['order', 'id'],
            },
        ),
    ]
