# Generated by Django 6.0.7 on 2026-07-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_portfolioitem_client_portfolioitem_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='aparat_embed_code',
            field=models.TextField(blank=True, help_text='کد embed کامل آپارات را از دکمه اشتراک\u200cگذاری در آپارات کپی و اینجا paste کنید', verbose_name='کد embed آپارات'),
        ),
    ]
