# Generated by Django 6.0.7 on 2026-07-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_portfolioitem_aparat_embed_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioimage',
            name='caption',
            field=models.CharField(blank=True, max_length=300, verbose_name='توضیحات تصویر'),
        ),
    ]
