# Generated by Django 6.0.7 on 2026-07-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HoldingCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام شرکت")),
                ("logo", models.ImageField(upload_to="holdings/", verbose_name="لوگو")),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "شرکت هلدینگ",
                "verbose_name_plural": "شرکت\u200cهای هلدینگ",
                "ordering": ["order", "name"],
            },
        ),
    ]
