# Generated by Django 6.0.7 on 2026-07-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holdings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="holdingcompany",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="holdings/", verbose_name="لوگو"
            ),
        ),
    ]
