# Generated by Django 6.0.7 on 2026-07-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0002_alter_holdingcompany_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='holdingcompany',
            name='url',
            field=models.URLField(blank=True, verbose_name='آدرس وبسایت'),
        ),
    ]
