# Generated by Django 6.0.7 on 2026-07-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="شماره تماس"),
                ),
                ("message", models.TextField(blank=True, verbose_name="متن درخواست")),
                (
                    "is_reviewed",
                    models.BooleanField(default=False, verbose_name="بررسی شده"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ثبت"),
                ),
            ],
            options={
                "verbose_name": "درخواست تماس",
                "verbose_name_plural": "درخواست\u200cهای تماس",
                "ordering": ["-created_at"],
            },
        ),
    ]
