# Generated by Django 6.0.7 on 2026-07-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='نام و نام خانوادگی'),
        ),
    ]
